### ISSUE TITLE
 DIV的等高布局

### ISSUE THREAD

**Issue by openks** [openks/blog#4]
# DIV的等高布局

> 实现等高列布局的思路：让内层DIV的高撑高外层DIV的高，从而使外层DIV的高相等。

HTML代码如下：

``` html
<div id="wrapper3" class="equal-height">
    <div id="wrapper2" class="equal-height">
        <div id="wrapper1" class="equal-height">
            <div id="inner3" class="equal-height">Column 3 </div>
            <div id="inner2" class="equal-height">Column 2 </div>
            <div id="inner1" class="equal-height">Column 1 </div>
        </div>
    </div>
</div>
```

CSS代码如下：

``` css
.equal-height {
    float: left;
    position: relative;
}
#wrapper1 {
    width: 100%;
    background-color: green;
    left: 30%;
}
#wrapper2 {
    width: 100%;
    background-color: blue;
    left: 20%;
}
#wrapper3 {
    width: 500px;
    background-color: red;
    overflow: hidden;
}
div#inner1 {
    width: 50%;
    right: 50%;
    overflow: hidden;
}
div#inner2 {
    right: 50%;
    width: 30%;
    overflow: hidden;
    height: 486px;
}
div#inner3 {
    right: 50%;
    width: 20%;
    overflow: hidden;
}
```

这样就能够轻松实现列1，列2，列3等高。具体思路：只要有任意一个列高度增加其他列高度也会增加（如果要对各列设置背景，只需对wrapper设置不同的背景色即可）
通过图片可以很容易的说明：
![图片](http://7xl9u9.com1.z0.glb.clouddn.com/2015111011429.png)
所有div全部使用相对布局，左侧浮动效果如上图
![图片](http://7xl9u9.com1.z0.glb.clouddn.com/2015111011443-1.png)
滚动条向右拉动后效果如上图
这时只需要把Column3,Column2,Column1分别向左移动50%(从Column3的左边看就是第二列加第三列宽度)，50%(从Column 2的右边看就是第一列宽度)，50%（即下面那张结合上面那张图column 1的右边看就是第一列的宽度）
具体css代码如下可参考：

``` css
.equal-height {
    float: left;
    position: relative;
}
#wrapper1 {
    width: 100%;
    height: 70px;
    background-color: green;
    left: 30%;
}
#wrapper2 {
    width: 100%;
    height: 120px;
    background-color: blue;
    left: 20%;
}
#wrapper3 {
    width: 500px;
    height: 200px;
    background-color: red;
    overflow: scroll;
}
div#inner1 {
    width: 50%;
    background: gray;
    overflow: hidden;
}
div#inner2 {
    width: 30%;
    background-color: aqua;
}
div#inner3 {
    width: 20%;
    background-color: yellow;
}
```

这种方法需要几个等高列就需要双倍的DOM对象。
